### ISSUE TITLE
Stateful Scenes show up as lighting bolts on HA restart

### ISSUE THREAD

**Issue by sayam93** [hugobloem/stateful_scenes#146]
Stateful scenes entities show up as lighting bolts whenever Home Assistant is restarted. Any stateful scene entity changes to a toggle switch only when the scene related to it is activated. I have been seeing this behaviour both on past and the latest version of Stateful scenes as well as HA. I am currently using 1.5.0 with HAOS 14 and HA Core 2024.12.0

**Comment by hugobloem** [comment]
This is because the state of the switch is `unknown` until either the entities in the scene update or you manually force it to update by pressing either button. Similar behaviour is seen in MQTT where entities are being added without them reporting their state until they are polled or you interact with them. 

If the Stateful Scene switch stays  in the unknown position for a long time it might be worth checking the entities in the scene to see whether they are not updating as expected.

**Comment by sayam93** [comment]
> This is because the state of the switch is `unknown` until either the entities in the scene update or you manually force it to update by pressing either button. Similar behaviour is seen in MQTT where entities are being added without them reporting their state until they are polled or you interact with them.
> 
> If the Stateful Scene switch stays in the unknown position for a long time it might be worth checking the entities in the scene to see whether they are not updating as expected.

Would it be possible to restore the switch state to the one that existed before restart?

**Comment by hugobloem** [comment]
Technically, yes. However, this would mean that the state may be incorrect if entities have changed during the reboot. 

You could try to toggle "ignore unavailable" on the stateful scene device page to see if that helps.

**Comment by sayam93** [comment]
> Technically, yes. However, this would mean that the state may be incorrect if entities have changed during the reboot.
> 
> You could try to toggle "ignore unavailable" on the stateful scene device page to see if that helps.

I understand your point. Is it possible to give a 'Persist state across Restarts' as an option just like the two existing option - restore on deactivate and ignore if unavailable?

Ignore if unavailable doesn't work in this scenario. I have it on already for my stateful scenes :)
