### ISSUE TITLE
Not recognizing state of scene when WLED Entity is used in scene

### ISSUE THREAD

**Issue by Haraldbbag** [hugobloem/stateful_scenes#37]
HI
First at all, this is a great tool. Thanks a lot for it.
Unfortunately I am unsing several WLED LED Stripes. As soon as one of them in part of a scene the scene will not be recognized as active, even if it is. 

Best regards Harald

**Comment by hugobloem** [comment]
Hi Harald,

I do not have WLED entities myself so could you please give me some more information to help me understand the issue. I assume the WLED strips are exposed as regular lights in HA, is this correct? If so, what states do they assume when on and off? Do you configure any other attributes?

BW,
Hugo

**Comment by robchandhok** [comment]
Thanks for the code!  Cool idea.

I'm seeing a similar behavior with some LED strips - but I think it's really anything that has more than an RGB color/on-off/brightness.  My scenes have Hue, Lifx, and Leviton lighting entities.  The scenes come on when you turn the switch on, but the state of the switch never stays on.

I think I understand your code for comparing attributes, and it looks like you do only compare the subset...so I'm confused as to why it is failing....I'm going to turn on debugging and see more.  Because I can't imagine what wouldn't work.....

**Comment by robchandhok** [comment]
Hi again @Haraldbbag ,

I think I have some idea of the issue - my observation is that the code checks for the scene equality BEFORE all the lights have changed state.  In my case, a Hue lamp takes a few seconds to fully turn off, but the scene equality is checked before that.  

What's the trigger to re-evaluate the state after the switch is turned 'on'?  Perhaps there needs to be a slight delay, as for some integrations there may be a gap between sending the command and the state coming back into the light entity itself. 

I can't think of an event to catch for an arbitrary scene to know when everything is done.  I have ZWave landscape lights that could take 3-5 seconds after you tell them "on" to actually look like they are turned on in their entity state.

Hope this makes sense.

**Comment by hugobloem** [comment]
Hi,

That may be the cause of the problems. I can add a periodic update (say 5 seconds after an entity has changed) such that those entities are checked again.

**Comment by robchandhok** [comment]
I think if you added a "post-event-delay" configuration item, value in `seconds`, with a value of zero being the same behavior as now, that would be a good compromise.  thanks!  I'm happy to test pre-release if that is useful.
